// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	scanSource: (path: string) => typedError<VolumeMeta[], AppError>(__TAURI_INVOKE("scan_source", { path })),
	scanCurrentSource: () => typedError<VolumeMeta[], AppError>(__TAURI_INVOKE("scan_current_source")),
	buildPipelinePlan: (options: ConvertOptions, edits: VolumeEdit[]) => typedError<PipelinePlan, AppError>(__TAURI_INVOKE("build_pipeline_plan", { options, edits })),
	convert: (options: ConvertOptions, edits: VolumeEdit[]) => typedError<null, AppError>(__TAURI_INVOKE("convert", { options, edits })),
	/**
	 *  Request cooperative cancellation of an in-flight `convert`.
	 *
	 *  Cancellation is checked between volumes and between encoded-image deliveries
	 *  inside a volume, so the request takes effect within ~one image's encode time
	 *  in the worst case (not mid-encode).
	 */
	cancelConversion: () => typedError<null, AppError>(__TAURI_INVOKE("cancel_conversion")),
	getDiscoverySettings: () => typedError<DiscoverySettings, AppError>(__TAURI_INVOKE("get_discovery_settings")),
	setDiscoverySettings: (settings: DiscoverySettings) => typedError<null, AppError>(__TAURI_INVOKE("set_discovery_settings", { settings })),
	suwayomiStatus: () => typedError<RuntimeState, AppError>(__TAURI_INVOKE("suwayomi_status")),
	suwayomiInstalledInfo: () => typedError<{
	version: string,
	size: number,
} | null, AppError>(__TAURI_INVOKE("suwayomi_installed_info")),
	suwayomiInstall: (version: string | null) => typedError<null, AppError>(__TAURI_INVOKE("suwayomi_install", { version })),
	suwayomiUninstall: () => typedError<null, AppError>(__TAURI_INVOKE("suwayomi_uninstall")),
	suwayomiCheckUpdate: () => typedError<UpdateInfo, AppError>(__TAURI_INVOKE("suwayomi_check_update")),
	suwayomiStart: () => typedError<number, AppError>(__TAURI_INVOKE("suwayomi_start")),
	suwayomiStop: () => typedError<null, AppError>(__TAURI_INVOKE("suwayomi_stop")),
	suwayomiRestart: () => typedError<number, AppError>(__TAURI_INVOKE("suwayomi_restart")),
	suwayomiResetData: () => typedError<null, AppError>(__TAURI_INVOKE("suwayomi_reset_data")),
	suwayomiOpenDataFolder: () => typedError<null, AppError>(__TAURI_INVOKE("suwayomi_open_data_folder")),
	listInstalledSources: () => typedError<SourceInfo[], AppError>(__TAURI_INVOKE("list_installed_sources")),
	listAvailableExtensions: () => typedError<ExtensionInfo[], AppError>(__TAURI_INVOKE("list_available_extensions")),
	installExtension: (pkg: string) => typedError<null, AppError>(__TAURI_INVOKE("install_extension", { pkg })),
	uninstallExtension: (pkg: string) => typedError<null, AppError>(__TAURI_INVOKE("uninstall_extension", { pkg })),
	searchSource: (sourceId: string, query: string, page: number) => typedError<SearchPage, AppError>(__TAURI_INVOKE("search_source", { sourceId, query, page })),
	listChapters: (mangaId: number) => typedError<ChapterMeta[], AppError>(__TAURI_INVOKE("list_chapters", { mangaId })),
	downloadSeries: (mangaId: number, chapters: ChapterMeta[], convertAfter: boolean) => typedError<null, AppError>(__TAURI_INVOKE("download_series", { mangaId, chapters, convertAfter })),
};

/** Events */
export const events = {
	chapterDownloadEvent: makeEvent<ChapterDownloadEvent>("chapter-download-event"),
	conversionCompleteEvent: makeEvent<ConversionCompleteEvent>("conversion-complete-event"),
	downloadCompleteEvent: makeEvent<DownloadCompleteEvent>("download-complete-event"),
	downloadStartEvent: makeEvent<DownloadStartEvent>("download-start-event"),
	imageProgressEvent: makeEvent<ImageProgressEvent>("image-progress-event"),
	scanProgressEvent: makeEvent<ScanProgressEvent>("scan-progress-event"),
	suwayomiInstallProgressEvent: makeEvent<SuwayomiInstallProgressEvent>("suwayomi-install-progress-event"),
	suwayomiStateChangedEvent: makeEvent<SuwayomiStateChangedEvent>("suwayomi-state-changed-event"),
	volumeCompleteEvent: makeEvent<VolumeCompleteEvent>("volume-complete-event"),
	volumeStartEvent: makeEvent<VolumeStartEvent>("volume-start-event"),
};

/* Types */
export type AppError = { kind: "core"; code: string; message: string; severity: ErrorSeverity; causes: string[] } | { kind: "convert"; code: string; message: string; severity: ErrorSeverity; causes: string[] } | { kind: "source"; code: string; message: string; severity: ErrorSeverity; causes: string[] } | { kind: "io"; message: string } | { kind: "json"; message: string } | { kind: "semaphore"; message: string } | { kind: "task"; message: string } | { kind: "open_path"; message: string } | { kind: "state_lock"; message: string } | { kind: "suwayomi_not_installed" } | { kind: "suwayomi_not_running" } | { kind: "suwayomi_starting" } | { kind: "suwayomi_runtime"; message: string } | { kind: "suwayomi_not_ready" } | { kind: "cancelled" } | { kind: "message"; message: string };

// How chapters/scan-volumes are grouped into output volumes.
export type BundleMode =
// Group pages by detected volume number.
"auto" |
// Merge everything into a single output volume.
"flatten";

export type ChapterDownloadEvent = {
	current_chapter: string,
	current: number,
	total: number,
	phase: ChapterDownloadPhase,
	tick: number,
};

// Phase of an in-progress chapter download batch.
export type ChapterDownloadPhase =
// Waiting for the next chapter to finish downloading.
"downloading" |
// A single chapter finished downloading.
"complete";

export type ChapterMeta = {
	id: number,
	name: string,
	chapter_number: number,
	// Volume parsed from the chapter name (Suwayomi does not expose a volume field).
	volume_number: number | null,
	scanlator: string | null,
	downloaded: boolean,
};

// Optional color enhancement for washed-out color pages.
export type ColorEnhanceMode =
// Leave colors untouched.
"Off" |
// Subtle contrast and saturation lift.
"Mild" |
// Moderate contrast and saturation lift.
"Balanced" |
// Stronger lift for very faded scans.
"Strong";

// Emitted when all volumes are done.
export type ConversionCompleteEvent = {
	successful: number,
	failed: number,
	duration_secs: number,
	total_pages: number,
	input_bytes: number,
	output_bytes: number,
	passthrough_pages: number,
	encoded_pages: number,
	fetch_ms: number,
	decode_ms: number,
	transform_ms: number,
	encode_ms: number,
	outputs: ConversionOutput[],
};

export type ConversionOutput = {
	volume_num: number,
	volume_name: string,
	path: string,
};

// Sent from frontend to the convert command.
export type ConvertOptions = {
	output_dir: string,
	output_name: string,
	create_directory: boolean,
	image_format: ImageFormat,
	max_width: number | null,
	force_reencode: boolean,
	clean_tones: boolean,
	color_enhance?: ColorEnhanceMode,
	sharpen?: SharpenMode,
	output_format: OutputFormat,
	direction: Direction,
	bundle: BundleMode,
	volume_separator: string,
	hide_single_volume: boolean,
};

// EPUB reading direction.
export type Direction =
// Left-to-right (Western comics, manhwa).
"Ltr" |
// Right-to-left (manga, manhua).
"Rtl";

export type DiscoverySettings = {
	enabled: boolean,
	installedVersion: string | null,
	autoStart: boolean,
	lastUpdateCheck: string | null,
	downloadDir?: string | null,
	extensionRepos?: string[],
};

export type DownloadCompleteEvent = {
	success: boolean,
	error: string | null,
	output_dir: string | null,
};

export type DownloadStartEvent = {
	series_title: string,
	total_chapters: number,
};

export type ErrorSeverity = "warning" | "recoverable" | "fatal";

export type ExtensionInfo = {
	pkg_name: string,
	name: string,
	lang: string | null,
	version_name: string | null,
	installed: boolean,
};

// Target image encoding format.
export type ImageFormat =
// AVIF (AV1 Image Format) — best compression, slowest encoding.
"Avif" |
// WebP — good compression, faster than AVIF.
"Webp" |
// Keep original format without re-encoding.
"Original";

// Emitted after each image is encoded and written.
export type ImageProgressEvent = {
	volume_num: number,
	current: number,
	total: number,
	elapsed_secs: number,
	pages_per_sec: number,
	estimated_remaining_secs: number | null,
	input_bytes: number,
	output_bytes: number,
	passthrough_pages: number,
	encoded_pages: number,
	fetch_ms: number,
	decode_ms: number,
	transform_ms: number,
	encode_ms: number,
};

export type InstallProgress = { phase: "downloading"; bytes: number; total: number | null } | { phase: "verifying" } | { phase: "extracting" } | { phase: "complete"; version: string };

export type InstalledInfo = {
	version: string,
	size: number,
};

// Output container format.
export type OutputFormat =
// Comic Book ZIP — widely supported by comic readers.
"Cbz" |
// EPUB 3 fixed-layout — e-readers and reading apps.
"Epub" |
// Raw directory — one flat folder per volume.
"Raw";

// One page entry from the page editor — sent from JS to convert.
export type PageEditEntry = {
	source: PageEditSource,
	excluded: boolean,
};

/**
 *  Where a single page in the editor comes from. Tagged enum on the wire:
 *  `{ "kind": "original", "page_index": 3, "source_volume_num": 1 }` or
 *  `{ "kind": "custom",   "path": "/abs/path.png" }`.
 */
export type PageEditSource = { kind: "original";
// Index into the scan_result pages for `source_volume_num`.
page_index: number;
// Which scan volume to look up `page_index` in. None = parent VolumeEdit's volume.
source_volume_num: number | null } | { kind: "custom"; path: string };

// Metadata for a single scanned page — sent to JS. No image bytes.
export type PageMeta = {
	volume_num: number,
	page_index: number,
	// `thasia://image?path={url_encoded_absolute_path}`
	url: string,
	file_name: string,
};

export type PipelineCostClass = "cheap" | "medium" | "expensive" | "experimental";

export type PipelinePlan = {
	totalPages: number,
	includedPages: number,
	excludedPages: number,
	addedPages: number,
	volumes: number,
	imageFormat: ImageFormat,
	outputFormat: OutputFormat,
	stages: PipelineStage[],
};

export type PipelineStage = {
	id: string,
	label: string,
	enabled: boolean,
	steps: PipelineStep[],
};

export type PipelineStep = {
	id: string,
	label: string,
	category: string,
	enabled: boolean,
	defaultEnabled: boolean,
	exclusiveGroup: string | null,
	conflicts: string[],
	effects: PipelineStepEffects,
	cost: PipelineCostClass,
};

export type PipelineStepEffects = {
	dimensions: boolean,
	pixels: boolean,
	alpha: boolean,
	metadata: boolean,
	passthrough: boolean,
};

export type RuntimeState = { state: "not_installed" } | { state: "not_running" } | { state: "starting" } | { state: "ready"; port: number } | { state: "error"; message: string };

// Emitted each time one image finishes scanning (for large archives).
export type ScanProgressEvent = {
	current: number,
	total: number,
};

export type SearchPage = {
	results: SearchResult[],
	has_next_page: boolean,
};

export type SearchResult = {
	id: number,
	title: string,
	thumbnail_url: string | null,
	initialized: boolean,
};

// Optional sharpening for soft scans.
export type SharpenMode =
// Leave sharpness untouched.
"Off" |
// Mild unsharp-mask pass.
"Mild";

export type SourceInfo = {
	id: string,
	name: string,
	lang: string | null,
};

export type SuwayomiInstallProgressEvent = {
	progress: InstallProgress,
};

export type SuwayomiStateChangedEvent = {
	state: RuntimeState,
};

export type UpdateInfo = {
	current_version: string | null,
	latest_version: string,
	available: boolean,
};

// Emitted when a volume finishes (success or failure).
export type VolumeCompleteEvent = {
	volume_num: number,
	success: boolean,
	error: string | null,
	output_path: string | null,
};

// The page editor's output for one volume — sent to convert.
export type VolumeEdit = {
	volume_num: number,
	// Pages in final display order (after drag reorder + excludes + additions).
	pages: PageEditEntry[],
};

// One volume's page metadata — returned by scan_source.
export type VolumeMeta = {
	// Sequential scan index — unique key used for page lookup in convert.
	volume_num: number,
	/**
	 *  Actual parsed volume number from the source folder names — used by the
	 *  frontend to compute the default chapter→volume grouping.
	 */
	source_volume_num: number,
	pages: PageMeta[],
};

// Emitted when a volume starts converting.
export type VolumeStartEvent = {
	volume_num: number,
	volume_name: string,
	total_volumes: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

