// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	scanSource: (path: string) => typedError<VolumeMeta[], string>(__TAURI_INVOKE("scan_source", { path })),
	convert: (options: ConvertOptions, edits: VolumeEdit[]) => typedError<null, string>(__TAURI_INVOKE("convert", { options, edits })),
};

/** Events */
export const events = {
	conversionCompleteEvent: makeEvent<ConversionCompleteEvent>("conversion-complete-event"),
	imageProgressEvent: makeEvent<ImageProgressEvent>("image-progress-event"),
	scanProgressEvent: makeEvent<ScanProgressEvent>("scan-progress-event"),
	volumeCompleteEvent: makeEvent<VolumeCompleteEvent>("volume-complete-event"),
	volumeStartEvent: makeEvent<VolumeStartEvent>("volume-start-event"),
};

/* Types */
export type BundleMode = "auto" | "flatten";

// Emitted when all volumes are done.
export type ConversionCompleteEvent = {
	successful: number,
	failed: number,
	duration_secs: number,
};

// Sent from frontend to the convert command.
export type ConvertOptions = {
	output_dir: string,
	output_name: string,
	create_directory: boolean,
	image_format: ImageFormat,
	max_width: number | null,
	output_format: OutputFormat,
	direction: Direction,
	bundle: BundleMode,
	volume_separator: string,
	hide_single_volume: boolean,
};

// EPUB reading direction.
export type Direction = 
// Left-to-right (Western comics, manhwa).
"Ltr" | 
// Right-to-left (manga, manhua).
"Rtl";

// Target image encoding format.
export type ImageFormat = 
// AVIF (AV1 Image Format) — best compression, slowest encoding.
"Avif" | 
// WebP — good compression, faster than AVIF.
"Webp" | 
// Keep original format without re-encoding.
"Original";

// Emitted after each image is encoded and written.
export type ImageProgressEvent = {
	volume_num: number,
	current: number,
	total: number,
};

// Output container format.
export type OutputFormat = 
// Comic Book ZIP — widely supported by comic readers.
"Cbz" | 
// EPUB 3 fixed-layout — e-readers and reading apps.
"Epub" | 
// Raw directory — one flat folder per volume.
"Raw";

// One page entry from the page editor — sent from JS to convert.
export type PageEditEntry = {
	/**
	 *  Index into the original scan_result pages for this volume.
	 *  None if this is a user-added custom image.
	 */
	original_page_index: number | null,
	/**
	 *  Which scan volume to look up original_page_index in.
	 *  Defaults to the parent VolumeEdit.volume_num; set explicitly when a page
	 *  has been moved from a different scan volume (e.g. after manual merge).
	 */
	source_volume_num: number | null,
	// Set for user-added custom images; None for scanned pages.
	custom_path: string | null,
	excluded: boolean,
};

// Metadata for a single scanned page — sent to JS. No image bytes.
export type PageMeta = {
	volume_num: number,
	page_index: number,
	// `thasia://image?path={url_encoded_absolute_path}`
	url: string,
	file_name: string,
};

// Emitted each time one image finishes scanning (for large archives).
export type ScanProgressEvent = {
	current: number,
	total: number,
};

// Emitted when a volume finishes (success or failure).
export type VolumeCompleteEvent = {
	volume_num: number,
	success: boolean,
	error: string | null,
};

// The page editor's output for one volume — sent to convert.
export type VolumeEdit = {
	volume_num: number,
	// Pages in final display order (after drag reorder + excludes + additions).
	pages: PageEditEntry[],
};

// One volume's page metadata — returned by scan_source.
export type VolumeMeta = {
	// Sequential scan index — unique key used for page lookup in convert.
	volume_num: number,
	/**
	 *  Actual parsed volume number from the source folder names — used by the
	 *  frontend to compute the default chapter→volume grouping.
	 */
	source_volume_num: number,
	pages: PageMeta[],
};

// Emitted when a volume starts converting.
export type VolumeStartEvent = {
	volume_num: number,
	volume_name: string,
	total_volumes: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

