
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async scanSource(path: string) : Promise<Result<VolumeMeta[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_source", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async convert(options: ConvertOptions, edits: VolumeEdit[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("convert", { options, edits }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
conversionCompleteEvent: ConversionCompleteEvent,
imageProgressEvent: ImageProgressEvent,
scanProgressEvent: ScanProgressEvent,
volumeCompleteEvent: VolumeCompleteEvent,
volumeStartEvent: VolumeStartEvent
}>({
conversionCompleteEvent: "conversion-complete-event",
imageProgressEvent: "image-progress-event",
scanProgressEvent: "scan-progress-event",
volumeCompleteEvent: "volume-complete-event",
volumeStartEvent: "volume-start-event"
})

/** user-defined constants **/



/** user-defined types **/

export type BundleMode = "auto" | "flatten"
/**
 * Emitted when all volumes are done.
 */
export type ConversionCompleteEvent = { successful: number; failed: number; duration_secs: number }
/**
 * Sent from frontend to the convert command.
 */
export type ConvertOptions = { output_dir: string; output_name: string; create_directory: boolean; image_format: ImageFormat; max_width: number | null; output_format: OutputFormat; direction: Direction; bundle: BundleMode; volume_separator: string; hide_single_volume: boolean }
/**
 * EPUB reading direction.
 */
export type Direction = 
/**
 * Left-to-right (Western comics, manhwa).
 */
"Ltr" | 
/**
 * Right-to-left (manga, manhua).
 */
"Rtl"
/**
 * Target image encoding format.
 */
export type ImageFormat = 
/**
 * AVIF (AV1 Image Format) — best compression, slowest encoding.
 */
"Avif" | 
/**
 * WebP — good compression, faster than AVIF.
 */
"Webp" | 
/**
 * Keep original format without re-encoding.
 */
"Original"
/**
 * Emitted after each image is encoded and written.
 */
export type ImageProgressEvent = { volume_num: number; current: number; total: number }
/**
 * Output container format.
 */
export type OutputFormat = 
/**
 * Comic Book ZIP — widely supported by comic readers.
 */
"Cbz" | 
/**
 * EPUB 3 fixed-layout — e-readers and reading apps.
 */
"Epub" | 
/**
 * Raw directory — one flat folder per volume.
 */
"Raw"
/**
 * One page entry from the page editor — sent from JS to convert.
 */
export type PageEditEntry = { 
/**
 * Index into the original scan_result pages for this volume.
 * None if this is a user-added custom image.
 */
original_page_index: number | null; 
/**
 * Which scan volume to look up original_page_index in.
 * Defaults to the parent VolumeEdit.volume_num; set explicitly when a page
 * has been moved from a different scan volume (e.g. after manual merge).
 */
source_volume_num: number | null; 
/**
 * Set for user-added custom images; None for scanned pages.
 */
custom_path: string | null; excluded: boolean }
/**
 * Metadata for a single scanned page — sent to JS. No image bytes.
 */
export type PageMeta = { volume_num: number; page_index: number; 
/**
 * `thasia://image?path={url_encoded_absolute_path}`
 */
url: string; file_name: string }
/**
 * Emitted each time one image finishes scanning (for large archives).
 */
export type ScanProgressEvent = { current: number; total: number }
/**
 * Emitted when a volume finishes (success or failure).
 */
export type VolumeCompleteEvent = { volume_num: number; success: boolean; error: string | null }
/**
 * The page editor's output for one volume — sent to convert.
 */
export type VolumeEdit = { volume_num: number; 
/**
 * Pages in final display order (after drag reorder + excludes + additions).
 */
pages: PageEditEntry[] }
/**
 * One volume's page metadata — returned by scan_source.
 */
export type VolumeMeta = { volume_num: number; pages: PageMeta[] }
/**
 * Emitted when a volume starts converting.
 */
export type VolumeStartEvent = { volume_num: number; volume_name: string; total_volumes: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
